Update README with my issues
Had a crash because ./tmp did not exist:

```
$ spark-submit --driver-memory=6G py/readPdfs.py
Using Spark's repl log4j profile: org/apache/spark/log4j-defaults-repl.properties
To adjust logging level use sc.setLogLevel("INFO")
15/12/08 19:34:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/12/08 19:34:25 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
15/12/08 19:34:25 ERROR SparkContext: Error initializing SparkContext.
java.io.FileNotFoundException: File file:/home/andre/prog/repos/Spark-DS-example/tmp does not exist
```